services:
  notification_queue_redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes # activates AOF (Append Only File) mode, which records
                                           # each operation on disk to ensure data persistence.
                                           # Without this, if the container stops, data may be lost.
  api-gateway:
    build: 
      context: ./api_gateway       # Folder where the code and Dockerfile are located
      dockerfile: Dockerfile       # Dockerfile file name (default)
    ports:
      - "8000:8000"
    environment:
      BASE_URL_USER_SERVICE: "http://user-service:8000"
      BASE_URL_PUBLISH_NOTIFICATION_SERVICE: "http://notification-publisher-service:8000"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    expose:
      - "8000" # only accessible internally by other containers
  notification-publisher-service:
    build:
      context: ./notification-publish-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      - notification_queue_redis
    environment:
      REDIS_HOST: notification_queue_redis
      REDIS_PORT: 6379
      BASE_URL_SERVICE_USER: "http://user-service:8000"